### PR TITLE
Attributes not begining with CUBA are system-managed and read-only

### PR DESCRIPTION
**Pull request by kitchoi**
Tests would fail, awaiting @mehdisadeghi's PR on changing some of the attributes back to fixed attributes.

### CODE REVIEW

**Comment by mehdisadeghi** [comment]
Thanks for the quick PR. 

Regarding the title, anything with no `CUBA.` in the beginning, is basically fixed metadata information and no variable at all.

**Comment by kitchoi** [comment]
@mehdisadeghi Thanks.  I corrected the title.

**Comment by kitchoi** [comment]
@mehdisadeghi Done.  Ready for review.

**Comment by mehdisadeghi** [comment]
@kitchoi It looks good to me.

**Pull request merged**
