### PR TITLE
Add CFD needed data

### PR DESCRIPTION
**Pull request by khiltunen**
This PR adds boundary condition TotalPressureCondition and new CUBA key NUMBER_OF_PHYSICS_STATES

### CODE REVIEW

**Comment by khiltunen** [comment]
@ahashibon please review

**Review by ahashibon — APPROVED** [review]
all tests passed! can be merged.

**Comment by stefanoborini** [comment]
what's the point of adding a CUBA key that you are not using anywhere?

**Comment by ahashibon** [comment]
@stefanoborini adding it is for using it! check the new open foam wrapper, soon it will have the branch where we use it.

**Pull request merged**
