### PR TITLE
Remove cuba from physics_equaiton attribute. #26

### PR DESCRIPTION
**Pull request by mehdisadeghi**

### CODE REVIEW

**Comment by mehdisadeghi** [comment]
@kitchoi @ahashibon Please review this PR.

**Comment by kitchoi** [comment]
With these changes some of the test cases are no longer relevant.  Could you remove those affected tests please?

**Comment by mehdisadeghi** [comment]
I updated the PR to reflect current tests.

**Comment by kitchoi** [comment]
> With these changes some of the test cases are no longer relevant. Could you remove those affected tests please?

Please ignore.

It looks good to me.

**Pull request merged**
